### PR TITLE
feat: 0.8.23 support

### PR DESCRIPTION
**Pull request by Evalir**
Blocked on https://github.com/nikitastupin/solc

### CODE REVIEW

**Comment by pcaversaccio** [comment]
https://github.com/nikitastupin/solc/commit/923ab4b852fadc00ffe87bb76fff21d0613bd280

**Review by mattsse — APPROVED** [review]

**Comment by mattsse** [comment]
looks like an error with new apple silicon build?

**Comment by Evalir** [comment]
Yeah no clue? It seems like it's not getting the 0.8.23 version from the list even though the URL changed, like if it were cached?

**Comment by mattsse** [comment]
missing 0.8.23 entry:

https://github.com/alloy-rs/solc-builds/blob/master/macosx/aarch64/list.json

**Comment by Evalir** [comment]
i am dumb >.<

rerunning ci

**Comment by mattsse** [comment]
updated real quick 🫡

**Comment by mattsse** [comment]
I introduced the same error too many times :D
that's why the foundry tests for latest version exist

**Comment by mattsse** [comment]
will publish once merged

**Pull request merged**
